version: '3'
services:
  client:
    build: ./client
    ports:
      - 80:80
    networks:
      - mynetwork
  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    networks:
      - mynetwork
  server:
    build: ./server
    ports:
      - 8084:8084
    networks:
      - mynetwork

networks:
  mynetwork: