version: '3'
services:
  client:
    build: ./client
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw    
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mongo:
    build: ./mongo
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - mynetwork
    volumes:
      - ./mongo/data:/data/db 
  server:
    build: ./server
    ports:
      - 8084:8084
    networks:
      - mynetwork

networks:
  mynetwork:
